[package]
name = "autofix"
version = "0.1.0"
authors = ["Alex Macleod <alex@macleod.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glacier = { path = ".." }
once_cell = "1.2.0"
reqwest = "0.9.21"
serde = "1.0.101"

[dependencies.git2]
version = "0.10.1"
default-features = false
features = ["https"]
