[package]
name = "labeler"
version = "0.1.0"
authors = ["Yuki Okushi <huyuumi.dev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.2.0"
regex = "1.3.1"
reqwest = "0.9.21"
serde = "1.0.101"
