name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: cargo run glacier
        run: cargo run

      - name: cargo check autofix
        run: cargo check -p autofix
